import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";
import { ConvexClientProvider } from "@/components/providers/convex-provider";
import { Badge } from "@/components/ui/badge";
import Navigation from "@/shared/Navigation";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("min-h-screen bg-background font-sans antialiased", inter.className)}>
        <ConvexClientProvider>
          <Badge className="m-4">New combo solution</Badge>
          <Navigation />
          {children}
        </ConvexClientProvider>
      </body>
    </html>
  );
}
